Added Events to front page
soybase/jekyll-soybase pull request #109
Opened 2024-03-11 00:02 UTC by jd-campbell

I added the following conferences/meetings

- CROPS 2024
- NAPB 2024
- PAG 2025

2024-03-11 21:32 UTC, StevenCannon-USDA reviewed
Looks good to me, but see one typo/minor error in the link to the CROPS conference

2024-03-11 21:32 UTC, StevenCannon-USDA commented on events/_posts/2024-06-03-CROPS.md
Minor change: "CROP Conference 2024" --> "CROPS Conference 2024"

2024-03-12 17:48 UTC, maxglycine requested changes
It looks great, just 2 of the three links give an error in FF "
Firefox Can’t Open This Page

To protect your security, www.hudsonalpha.org will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window."

Maybe make the link open in a separate window using target="_blank"?

The PAG link opens a new window and that's fine with me.

2024-03-13 20:28 UTC, closed without merging

2024-03-13 20:37 UTC, jd-campbell commented
@maxglycine -- the  index.html file for events is found under the event folder.