Rearranged about the soybase genetic maps under community
soybase/jekyll-soybase pull request #57
Opened 2023-11-14 17:46 UTC by weihuang12

Removed "about the SoyBase Genetic maps" under community, and added a link "Details about the SoyBase genetic maps" to MAPS. Changed GCViT URL link under MAPS.

2023-11-14 22:34 UTC, maxglycine requested changes
OK, under the menu item "about & contact", I found a link "genetic maps and genome nomenclature" link.  That link lead me to the page "About the SoyBase Genetic Maps" which talks about the genetic map and sequence map (GmGWAS).   This page should also be linked to from  "Maps" =>"Genetic Map Resources for Soybean". There is a dead link "Details about the SoyBase genetic maps that should go to the "About the SoyBase Genetic Maps" (/about/about_maps) page ( I think).  As far as I can see, there is no link to the page "Genetic Maps and Genome Nomenclature" from the "Community" menu item.

2023-11-14 23:20 UTC, weihuang12 commented
To Rex's request:  The "Details about the SoyBase genetic maps" under "MAPS" is linked to "Genetic maps and map nomenclature" under the menu item "about & contract",  and is not a dead link.
 I removed "About the SoyBase Genetic Maps" under "Community" ( I thought it was redundant), but I will add it back with link to "Genetic maps and map nomenclature".

2023-11-15 21:14 UTC, StevenCannon-USDA reviewed
The suggestion to move "About the SoyBase Genetic Maps" from the community page (under the "Communications" heading) was from me. @maxglycine - do you really want an "about maps" page under "Communications"? It seems to me that the maps page is a better place to link that from.

I also suggest removing the link to the "[2009 Soybean Genomic Sequence Assembly Announcement](https://soybase.org/community/about_sequence_map.php)" altogether, since that is now VERY old news.

2023-11-15 22:32 UTC, maxglycine commented
@StevenCannon-USDA I did not suggest putting the link under “community” in the “communications” sub-section. I believe @weihuang12 did that. If it was up to me, the only reference would be under the “maps” menu item.

yes, we should drop the https://soybase.org/community/about_sequence_map.php link for just the reason you pointed out.

Anything else?

2023-11-16 02:49 UTC, StevenCannon-USDA reviewed
Sorry for the confusion, Wei.
One more change to make on the community page (remove the about_maps link).

2023-11-16 02:49 UTC, StevenCannon-USDA commented on _data/community.yml
On this file, please delete lines 31 and 32: /about/about_maps and "About the SoyBase Genetic Maps"

2023-11-16 15:48 UTC, StevenCannon-USDA approved these changes
Looks good to me. I'll approve and merge.

2023-11-16 15:48 UTC, StevenCannon-USDA approved these changes

2023-11-16 15:49 UTC, StevenCannon-USDA approved these changes

2023-11-16 15:51 UTC, StevenCannon-USDA commented
Hmm. Seems that @maxglycine also has to review and approve. Rex - I think that is because you requested changes. My approval wasn't sufficient to allow a merge.

2023-11-16 18:48 UTC, maxglycine approved these changes

2023-11-16 18:49 UTC, maxglycine commented
I have approved

2023-11-16 18:50 UTC, maxglycine commented
@StevenCannon-USDA and @weihuang12 I have approved

2023-11-16 18:50 UTC, merged

2023-11-16 18:51 UTC, StevenCannon-USDA commented
Thanks, @weihuang12 and @maxglycine .
I have merged this branch and will delete it now.