Responsive banner2
soybase/jekyll-soybase pull request #79
Opened 2024-01-03 22:20 UTC by StevenCannon-USDA

Add _includes/navbar-lower-menu.html to recover banner/nav responsive behavior. Also (re)-fix two minor yml errors.

2024-01-03 22:38 UTC, StevenCannon-USDA commented
@nathanweeks - I have added you for this PR review because I am puzzled by the reported conflict for _includes/navbar-lower-menu.html. 
It looks to me like that file is absent from "main", so there shouldn't be a conflict(?) 
I suspect this means that I am not understanding the relation to the theme. Is this navbar-lower-menu.html now not local to jekyll-soybase?

2024-01-04 15:53 UTC, nathanweeks commented
> @nathanweeks - I have added you for this PR review because I am puzzled by the reported conflict for _includes/navbar-lower-menu.html. It looks to me like that file is absent from "main", so there shouldn't be a conflict(?) I suspect this means that I am not understanding the relation to the theme. Is this navbar-lower-menu.html now not local to jekyll-soybase?

I'd guess responsive-banner2 wasn't branched off of main (or was branched from an older commit of main, before _includes/navbar-lower-menu.html was removed)? Otherwise, it would show the addition of a new file _includes/navbar-lower-menu.html, instead of a [one-line whitespace change](https://github.com/soybase/jekyll-soybase/pull/79/files#diff-a77fd1eb06001838724faa10ca6d6c3090e3a87cb1ef5126ca4898f7e47446bf) (plus a couple other misc. whitespace differences in other files). If that's the case, one possible solution is to copy the _includes/navbar-lower-menu.html from your (local) responsive-banner2 branch to somewhere outside the repo, rename your local responsive-banner2 branch (e.g., responsive-banner2.bak), switch to main, `git pull origin main` to update your local main, `git branch responsive-banner2` to create a new responsive-banner2, copy & git-add the _includes/navbar-lower-menu.html into that branch, commit, and force-push to the remote responsive-banner2.

2024-01-04 16:16 UTC, StevenCannon-USDA commented
Thanks for the instructions, @nathanweeks. Your suggestion seemed to work. Ready for review now.

2024-01-04 16:41 UTC, nathanweeks requested changes

2024-01-04 16:41 UTC, nathanweeks commented on _includes/navbar.html
This file is identical to the version in the theme (_themes/jekyll-theme-legumeinfo/_includes/navbar.html). Until it's needed to explicitly override the theme version, I'll suggest removing this file to avoid accidental site UI/configuration drift from the upstream/theme.

2024-01-04 16:53 UTC, StevenCannon-USDA commented on _includes/navbar.html
I see. Agree. It is removed now.

2024-01-04 20:16 UTC, nathanweeks approved these changes

2024-01-04 20:18 UTC, merged